### ISSUE TITLE
Message: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID)) 

### ISSUE THREAD

**Issue by noad24** [NumyAddon/MacroToolkit#59] opened 2024-07-27 13:47 UTC
when i click toolkit there have this error

Message: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
Time: Sat Jul 27 16:45:47 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "@Interface/AddOns/MacroToolkit/modules/parser.lua"]:44: in function <Interface/AddOns/MacroToolkit/modules/parser.lua:32>
[string "@Interface/AddOns/MacroToolkit/modules/parser.lua"]:60: in function <Interface/AddOns/MacroToolkit/modules/parser.lua:55>
[string "@Interface/AddOns/MacroToolkit/modules/parser.lua"]:314: in function <Interface/AddOns/MacroToolkit/modules/parser.lua:306>
[string "@Interface/AddOns/MacroToolkit/modules/parser.lua"]:836: in function `ParseMacro'
[string "@Interface/AddOns/MacroToolkit/MacroToolkit.lua"]:502: in function `FormatMacro'
[string "@Interface/AddOns/MacroToolkit/MacroToolkit.lua"]:851: in function `MacroFrameUpdate'
[string "@Interface/AddOns/MacroToolkit/modules/mainframe.lua"]:726: in function <Interface/AddOns/MacroToolkit/modules/mainframe.lua:718>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/MacroToolkit/MacroToolkit.lua"]:135: in function <Interface/AddOns/MacroToolkit/MacroToolkit.lua:133>

Locals: treeId = 793
nodes = <table> {
 1 = 82043
 2 = 82045
 3 = 82046
 4 = 82047
 5 = 82048
 6 = 82049
 7 = 82050
 8 = 82051
 9 = 82052
 10 = 82053
 11 = 82054
 12 = 82055
 13 = 82056
 14 = 82057
 15 = 82058
 16 = 82059
 17 = 82060
 18 = 82061
 19 = 82062
 20 = 82063
 21 = 82064
 22 = 82065
 23 = 82066
 24 = 82067
 25 = 82068
 26 = 82069
 27 = 82070
 28 = 82071
 29 = 82072
 30 = 82073
 31 = 82074
 32 = 82075
 33 = 82076
 34 = 82077
 35 = 82079
 36 = 82080
 37 = 82081
 38 = 82082
 39 = 82083
 40 = 82084
 41 = 82085
 42 = 82086
 43 = 82088
 44 = 82090
 45 = 82091
 46 = 82092
 47 = 82093
 48 = 82094
 49 = 82095
 50 = 82096
 51 = 82098
 52 = 82099
 53 = 82100
 54 = 82101
 55 = 82102
 56 = 82103
 57 = 82104
 58 = 82105
 59 = 82106
 60 = 82107
 61 = 82108
 62 = 82109
 63 = 82110
 64 = 82111
 65 = 82112
 66 = 82113
 67 = 82114
 68 = 82115
 69 = 82116
 70 = 82117
 71 = 82118
 72 = 82119
 73 = 82120
 74 = 82121
 75 = 82122
 76 = 82123
 77 = 82124
 78 = 82126
 79 = 82127
 80 = 82128
 81 = 82129
 82 = 82130
 83 = 82131
 84 = 82132
 85 = 82133
 86 = 82134
 87 = 82135
 88 = 82136
 89 = 82137
 90 = 82138
 91 = 82139
 92 = 82140
 93 = 82141
 94 = 82142
 95 = 82143
 96 = 82144
 97 = 82145
 98 = 82146
 99 = 82147
 100 = 82148
 101 = 82149
 102 = 82151
 103 = 82152
 104 = 82153
 105 = 82154
 106 = 82155
 107 = 82156
 108 = 82157
 109 = 82158
 110 = 82159
 111 = 82160
 112 = 82161
 113 = 82162
 114 = 82198
 115 = 82199
 116 = 82200
 117 = 82201
 118 = 82202
 119 = 82203
 120 = 82204
 121 = 82205
 122 = 82206
 123 = 82207
 124 = 82208
 125 = 82209
 126 = 82210
 127 = 82211
 128 = 82213
 129 = 82214
 130 = 82215
 131 = 82217
 132 = 82218
 133 = 82219
 134 = 82220
 135 = 82221
 136 = 82222
 137 = 82223
 138 = 82224
 139 = 82225
 140 = 82227
 141 = 82228
 142 = 82229
 143 = 82230
 144 = 82231
 145 = 82232
 146 = 82233
 147 = 82234
 148 = 82235
 149 = 82236
 150 = 82237
 151 = 82238
 152 = 82239
 153 = 82240
 154 = 82241
 155 = 82242
 156 = 82243
 157 = 82244
 158 = 82246
 159 = 88199
 160 = 88200
 161 = 88201
 162 = 88202
 163 = 88203
 164 = 88204
 165 = 88206
 166 = 88207
 167 = 88208
 168 = 88209
 169 = 88210
 170 = 88211
 171 = 88212
 172 = 88213
 173 = 88214
 174 = 88215
 175 = 88216
 176 = 88217
 177 = 88218
 178 = 88219
 179 = 88220
 180 = 88221
 181 = 88222
 182 = 88223
 183 = 88224
 184 = 88225
 185 = 88226
 186 = 88227
 187 = 88228
 188 = 88229
 189 = 88231
 190 = 88232
 191 = 88234
 192 = 88235
 193 = 88236
 194 = 91040
 195 = 91041
 196 = 91044
 197 = 91046
 198 = 91047
 199 = 91048
 200 = 92226
 201 = 92227
 202 = 92229
 203 = 92585
 204 = 92586
 205 = 92587
 206 = 92588
 207 = 92641
 208 = 92674
 209 = 93714
 210 = 94535
 211 = 94585
 212 = 94586
 213 = 94587
 214 = 94588
 215 = 94590
 216 = 94591
 217 = 94592
 218 = 94593
 219 = 9459

**Comment by noad24** [comment] 2024-07-27 13:53
i cant extend my macros

**Comment by Numynum** [comment] 2024-07-27 14:34
duplicate of #58 
and see the addon description why you can't extend macros (tl;dr: blame blizzard)

**Closed by Numynum** 2024-07-27 14:34 UTC
